import { TerserOptions } from 'vite'

export const terserOptions: TerserOptions = {
  ecma: 2020,
  safari10: false,
  ie8: false,

  parse: {
    bare_returns: false,
    shebang: false,
    html5_comments: false,
  },
  compress: {
    ecma: 2020,

    defaults: false,
    arrows: true,
    arguments: true,
    booleans: true,
    booleans_as_integers: false,
    collapse_vars: true,
    comparisons: true,
    computed_props: true,
    conditionals: true,
    dead_code: true,
    directives: true,
    drop_console: true,
    drop_debugger: true,
    evaluate: true,
    expression: true,
    global_defs: {},
    hoist_funs: true,
    hoist_props: true,
    hoist_vars: true,
    if_return: true,
    inline: 3,
    join_vars: true,
    keep_classnames: false,
    keep_fargs: false,
    keep_fnames: false,
    keep_infinity: false,
    loops: true,
    module: true,
    negate_iife: true,
    passes: 20,
    properties: true,
    pure_getters: true,
    pure_new: true,
    reduce_vars: true,
    reduce_funcs: true,
    sequences: 10000,
    side_effects: true,
    switches: true,
    toplevel: true,
    top_retain: [],
    typeofs: true,
    unsafe: true,
    unsafe_arrows: true,
    unsafe_comps: true,
    unsafe_Function: true,
    unsafe_math: true,
    unsafe_symbols: true,
    unsafe_methods: true,
    unsafe_proto: true,
    unsafe_regexp: true,
    unsafe_undefined: true,
    unused: true,
  },
  mangle: {
    safari10: false,

    eval: true,
    toplevel: true,
    properties: {},
  },
  format: {
    ecma: 2020,
    ie8: false,
    safari10: false,
    webkit: false,

    ascii_only: true,
    braces: false,
    comments: false,
    keep_numbers: false,
    indent_level: 0,
    indent_start: 0,
    inline_script: true,
    keep_quoted_props: false,
    max_line_len: false,
    preserve_annotations: false,
    quote_keys: false,
    semicolons: true,
    shorthand: true,
    shebang: false,
    wrap_iife: false,
    wrap_func_args: false,
  },
};
